### ISSUE TITLE
MD tag

### ISSUE THREAD

**Issue by llq0325** [danshea/IntroMap#1]
Hi Daniel,

I got a problem when IntroMap runing createMatchVector function.
The BAM file I used is generated by BWA-mem, which didn't include MD tag. I use SAMTOOLS calmd to add MD tag, but it seems that IntroMap can't recognized the format.
I wonder if IntroMap can only take BOWTIE alignment as input?

regards,

llq

**Comment by danshea** [comment]
Hi llq,

I'll have to take a look at what the `calmd` flag outputs and see why IntroMap was unable to parse it. The parsing is not particularly robust, and it was only tested on bowtie2 output.

If you have a small example of the output generated using `samtools calmd` that would help a lot with troubleshooting the issue. Also, if you could tell me what the error message was, I'll try and take a look at it when I have a chance.

In the meantime, you could try alignment of your reads with bowtie2 and see if that works for you.

Warmest Regards,
Dan

**Comment by llq0325** [comment]
Hi Dan,

Thanks for replying.
Here are some line in SAM format.
>>>>>>>>>>>>>>>>>>>>>>>
HISEQ:374:C5EVKACXX:7:2116:15533:42550#1:N:0:CAATGTA    99      1      95      15      18M1I23M2I42M   =       298     303     AACATACAAATATGTAACTCTAAAAAATTTAACCATAGAAAAACCCACATAATTTAATATATTATAACCCTATGTACGTCGTGCAT  <@@DD>DDFFHFDIAHIIGHGEGIAFHIIBAFEEHICHGGHB@D=?)7?F@<C48@C@BDEG;CAD@;.=@CCE>.==>>88<=?@  RG:Z:ABGSA0380_1        NM:i:12 AS:i:27 XS:i:29 MD:Z:15G3C0C8T5T8A1A3C7C24
HISEQ:378:C5EMTACXX:7:2115:20070:21765#2:N:0:CGATGTA    163     1      117     21      19M2I79M        =       357     340     AAAATTTAACCATAGAAAAACCCCAATAATTTAATATATTATAACCCTATGTACGTCGTGCATTAATTGCTAGTCCCCATGCATATAAGCATGTACATAT    CCCFFFFFGHHHHIJIIIJH@ACF+AEGGGIGIGIJIJJIFIJJJGGEGI000?BBGGGIIBHGHGIIIIGHHFHHFFDDEE@>C@D@C>@CDADCCDCD    RG:Z:ABGSA0380_1        NM:i:8  AS:i:64 XS:i:65 MD:Z:7T5T7A2A3C7C61
HISEQ:378:C5EMTACXX:1:1110:3693:66754#1:N:0:CGATGTA     99      1      140     43      100M    =       337     297     ATAATTTAATATATTATAACCCTATGTACGTCGTACATTAATTGCTAGTCCCCATGCATATAAGCATGTACATATTATTATTAATATTACATAGTACATA    @@@FDDDF<?D?DECBFGHIGIDGGDHGIGII>G?FCHHE<D>F@FHG?B?FHIEBFGGHG>FFACG3.)/==CC@;CAG3?EAC3?>;3;C@36>>>@B    RG:Z:ABGSA0380_1        NM:i:4  AS:i:84 XS:i:80 MD:Z:1A3C7C20G65
HISEQ:378:C5EMTACXX:3:1109:18622:14355#1:N:0:CGATGTA    99      1      140     43      100M    =       323     266     ATAATTTAATATATTATAACCCTATGTACGTCGTGCATTAATTGCTAGTCCCCATGCATATAAGCATGTACATATTATTATTAATATTACATAGTACATA    @CCFFFFFGHHGHJJIJJJJGIIJJJIIJJIIIFGIGIJIIJJJIIJJIJIJIJIIIHHIIIHIDGGCAHIIJBHHEIFEEEHCHFDD;>?@CCACDDEA    RG:Z:ABGSA0380_1        NM:i:3  AS:i:89 XS:i:85 MD:Z:1A3C7C86
>>>>>>>>>>>>>>>>>>>>>>>>>>>

below is the error message
>>>>>>>>>>>>>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "./IntroMap.py", line 316, in <module>
    main()
  File "./IntroMap.py", line 309, in main
    infiles = writeLowessToFiles(args.infile, args.reference, args.outfile, frac=args.frac)
  File "./IntroMap.py", line 152, in writeLowessToFiles
    recordCount, refScores = calculateScores(infile, reference)
  File "./IntroMap.py", line 129, in calculateScores
    matchVector = createMatchVector(alignedSegment)
  File "./IntroMap.py", line 65, in createMatchVector
    for c in mdString:
UnboundLocalError: local variable 'mdString' referenced before assignment
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

llq

**Comment by danshea** [comment]
Hi llq,

The tag looks correct.
For reference, here is what some bowtie2 entries look like:

NS500733:84:HT733BGXX:1:11101:26506:1066        99      A09     37687251        42      74M     =       37687530        353     GAGATNACTGATTAATCAGGAGCCTAGACTAATTTTTTTATCACCTACCACGATTTCTTATATACTGTTAAAAA      AAA6A#EEEEEEE6EEAEE/EEAAEEEEAEEEE6AEEE/EEE/<A/E<//A/E/AEEEEEEEEEEEAEEEEAEA      AS:i:-13        XN:i:0  XM:i:5  XO:i:0  XG:i:0  NM:i:5  **MD:Z:5T32G3C5A0C24**      YS:i:0  YT:Z:CP
NS500733:84:HT733BGXX:1:11101:26506:1066        147     A09     37687530        42      74M     =       37687251        -353    TAGTTCTTTTGGTTCAAGTCTGAACACTAACCTTTGGTGAGCCTTCCAGAGCGTTGGTGCAGTAGAGCCTAGCA      /AE</EE<AEEEEA//EA/A/EEEAE//AEE/A6EEE/EEEAE///EE/EEAA//E/6EEEE/EEAEEE6A/AA      AS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0  NM:i:0  **MD:Z:74** YS:i:-13        YT:Z:CP
NS500733:84:HT733BGXX:1:11101:19015:1058        83      A09     12969457        1       75M     =       12969129        -403    AAGTCGTCTGGTCAACGCAGAGGTTATTTTTGCAATTGACTTTGAAATCTGTAACCTGAGACGACTGAANGTTAA     /EAEE6EE/A</EEEEAEEAEE/EEEEEEEEEEEEEEEAEEEEAEEE/EAEEEEEE6AEEEEE6EE6EE#AAAAA     AS:i:-1 XS:i:-1 XN:i:0  XM:i:1  XO:i:0  XG:i:0  NM:i:1  **MD:Z:69A5**       YS:i:-4 YT:Z:CP

I am wondering if pysam is failing to fetch the tag from the aligned segment for some reason?
i.e. - This part of the code (lines 63 - 64)
<pre>
if alignedSegment.has_tag('MD'):
    mdString = alignedSegment.get_tag('MD')
</pre>

I'm not sure how the `has_tag` method works internally in `pysam` (which I how I parse the tags out of the BAM file). I'll need to look at pysam source to figure that out, but I suspect the `has_tag` method is returning `False` for some reason and thus failing to set `mdString`. (As an aside, I should probably have written this function in a better manner to throw an error when no MD tags are present in the input. I'll have to put that particular TODO on my ever growing list of things to do!)

I think I have some `bwa` aligned files lying around from another project. I'll take a look at trying to add MD tags to them using `samtools calmd`, and then seeing what pysam's `has_tag` method returns on the aligned segments.

Thanks for bringing this to my attention.

Warmest Regards,
Dan

**Comment by llq0325** [comment]
Hi Dan,

I know where the problem is. It turns out that, for some of the reads, samtools can't calculate a MD.
I modified the code a little bit: 

if alignedSegment.has_tag('MD'):
    mdString = alignedSegment.get_tag('MD')
else:
    mdString = ""

and it works fine now. :)

Also, some advice:
In the plot function, it assume the output prefix is like "queryname.refname", which maybe a little confussing at the first time.

Thank you!

llq

**Comment by danshea** [comment]
Hi llq,

Thanks for the update. I'm glad you were able to resolve the issue.

Regarding the plotting function, you are correct it does make some assumptions about the output prefix. I need to update the documentation more once I have a chance to do so. The code is not really standalone software yet, and is why we released it as a methodology paper.

I'm in last few months of my studies right now (and defending in 3 weeks), so I will leave this issue open so that I don't forget about it. When I have the opportunity, I will try to improve upon it further. Thank you very much for taking the time to try it out, and thank you for your suggestions!

Warmest Regards,
Dan

**Comment by llq0325** [comment]
I am going to play with it in the near term. I will keep you informed if there are any other issue.

Good luck with your defence!

llq

**Comment by danshea** [comment]
I've added an error message and force a exit status of 1 when the program encounters an alignedSegment that does not contain an MD tag.

Warmest Regards,
Dan
