### ISSUE TITLE
create conda environment

### ISSUE THREAD

**Issue by rfinkers** [danshea/IntroMap#2]
To allow successful creation of the conda environment, i had to change the following in the file: IntroMap_conda_environment.yml

-- pysam=0.10.0=py27_2
+- pysam=0.10.0

**Comment by danshea** [comment]
Thanks Richard! I think conda's yaml maybe changed underneath me between versions. I'll update the file and test it out when I have a chance.

**Comment by danshea** [comment]
Updated the config.
