### ISSUE TITLE
fail to create conda environment 

### ISSUE THREAD

**Issue by liufy11** [danshea/IntroMap#3]
when I create the conda environment with the command "conda env create -f IntroMap_conda_environment.yml''
It takes too long to download qt-5.6.2、scipy-0.19.0、scipy-0.19.0 , and at last failed to create the environment .
Is anybody know how to solve the problem ? or can I install Intromap without conda ?

**Comment by danshea** [comment]
Hi liufy11,

Conda is not required to use the script. it just provides the environment with which the script was tested. It should work on more recent versions of the libraries used (scipy, etc.) But it has not been tested.

I hope that helps.

**Comment by liufy11** [comment]
Thanks for you answer ,I have run Intromap without create the environment .but I meet with another problem
 File "~/Biosoft/IntroMap/IntroMap.py", line 65, in createMatchVector
    for c in mdString:
UnboundLocalError: local variable 'mdString' referenced before assignment

How to deal with the problem??? many thanks

**Comment by danshea** [comment]
Please check to ensure that the mapped reads have associated MD tags. You can check the other open issue [here](https://github.com/danshea/IntroMap/issues/1) for details.

Warmest Regards,
Dan

**Comment by liufy11** [comment]
en, to simplify questions, I run my data with Bowtie2 . and then apply Intromap to get introgression . the command is 
"nohup ~/Biosoft/IntroMap/IntroMap.py -t 24 -i ~/Test/Analysis/Bowtie2/R01R05.rmdup.bam -r ~/Test/Ref/Brassica_napus/Brassica_napus_v4.1.chromosomes.fa -o R01R05.intromap 2>R01.error"

the runing abort; the error is   XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server "localhost:14.0" after 594 requests (594 known processed) with 0 events remaining.

At last, create files end with .intromap for every chromosome but only  intromap.predicted.out and intromap_predicted.png. for chrA01 .
I didn't use conda to create my environment, and use multi threading to save time.
