### ISSUE TITLE
program interruption: fatal IO error 11

### ISSUE THREAD

**Issue by liufy11** [danshea/IntroMap#4]
Intromap aborts when It begin to create the picture for chrA02，It have create pictures for chrA01 and chrA01_random. so I think the command is correct, and I didn't use conda to create my environment . 
the error is "XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server "localhost:10.0" after 4599 requests (4599 known processed) with 31 events remaining."
What should I do ?

**Comment by danshea** [comment]
Hi,
This is likely a remote display issue with X11 from what I can discern from the error message.
Are you running IntroMap remotely over ssh with X forwarding by any chance?
You can check [here](https://www.google.com/search?client=ubuntu&channel=fs&q=XIO%3A+fatal+IO+error+11+%28Resource+temporarily+unavailable%29+on+X+server+%22localhost%3A10.0&ie=utf-8&oe=utf-8).
It seems to be related to issues with X library versions.

It is not related to the IntroMap code itself, but if you need to run remotely over ssh, you could try commenting out the plotting routine and just generating the prediction outputs by commenting out the following lines in the IntroMap.py file.

Line 276 - 287 in the plotFromLowessFiles function.

In that case, it won't try to generate graphical plots, just files containing the predicted regions.
Hope that helps.

**Comment by liufy11** [comment]
According to you  direction , I  have got all the  predicted regions for my sample. but I still want to get the pictures to see  the reliability of  predicted regions and shows my results . so I will learn to solve the "fatal IO error " problem . and if I failed to do that , Can I get  pictures directly using  files end with .intromap produced by  IntroMap.py before ?

**Comment by danshea** [comment]
Hi liufy11,

Recently, I updated the program to allow the use of pre-computed outputs for plotting. You can try to copy the pre-computed files to a local machine and pass the files to the --pre argument. Sorry I couldn't be of more help with your X11 issues. I hope that works for you.

Warmest Regards,
Dan

**Comment by liufy11** [comment]
Thanks very much, I will try it if neccessary! 



------------------ 原始邮件 ------------------
发件人: "Dan Shea"<notifications@github.com>;
发送时间: 2019年7月1日(星期一) 下午5:12
收件人: "danshea/IntroMap"<IntroMap@noreply.github.com>;
抄送: "fangying"<365698105@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [danshea/IntroMap] program interruption: fatal IO error 11 (#4)




Hi liufy11,
 
Recently, I updated the program to allow the use of pre-computed outputs for plotting. You can try to copy the pre-computed files to a local machine and pass the files to the --pre argument. Sorry I couldn't be of more help with your X11 issues. I hope that works for you.
 
Warmest Regards,
 Dan
