### ISSUE TITLE
Conda environment file IntroMap_conda_environment.yml is broken

### ISSUE THREAD

**Issue by dansun78** [danshea/IntroMap#5]
I detected this issue when I attempt to deploy IntroMap on our Linux cluster for a bioinformatician.

When deploying IntroMap by using the provided Conda environment file `IntroMap_conda_environment.yml`, Conda fails to deploy the environment but generates the following error instead.

```shell
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - cairo==1.14.8=0
  - readline==6.2=2
  - openssl==1.0.2k=1
  - pathlib2==2.2.0=py27_0
  - get_terminal_size==1.0.0=py27_0
  - ssl_match_hostname==3.4.0.2=py27_1
  - tk==8.5.18=0
  - pyparsing==2.1.4=py27_0
  - scandir==1.5=py27_0
  - glib==2.50.2=1
  - markupsafe==0.23=py27_2
  - pycairo==1.10.0=py27_0
  - path.py==10.1=py27_0
  - numpy==1.12.0=py27_0
  - simplegeneric==0.8.1=py27_1
  - mkl==2017.0.1=0
  - pcre==8.39=1
  - matplotlib==2.0.0=np112py27_0
  - scipy==0.19.0=np112py27_0
  - libpng==1.6.27=0
  - freetype==2.5.5=2
  - pyzmq==16.0.2=py27_0
  - jpeg==9b=0
  - icu==54.1=0
  - statsmodels==0.8.0=np112py27_0
  - qt==5.6.2=3
  - biopython==1.68=np112py27_0
```

As a workaround, one can strip all version numbers in the Conda environment (`sed 's/=.*//'` will do the trick), and let Conda to resolve all package dependencies by using the latest versions possible.  However, it is not an ideal approach and it may accidently introduce incompatibility issues.

I would recommend revising the Conda environment to only include software packages that IntroMap depends on immediately with their minimal or/and maximum required version and also remove all other dependencies.  This will significantly improve the maintainability, portability and longevity of this Conda environment file.

**Comment by danshea** [comment]
Hi Dan,

Thanks for the notification. I haven't looked at this software in a while, I've since moved from academic research to industry. I will add a revised yaml file to the archive (with the caveat that nothing has been tested beyond the versions listed in the original file).

**Comment by danshea** [comment]
Made changes, revised & updated the README.
