### ISSUE TITLE
No MD tag found

### ISSUE THREAD

**Issue by nirwan1265** [danshea/IntroMap#7]
I am getting this error:
[ntanduk@c050n01 Introgress]$ ./IntroMap.py -i PN2_SID100_bowtie2.bam -r chr1_reference_Zm_v5.fa -o PN2_SN100 -t 0.90 -b True -f 0.05
ERROR: No MD tag found! Please ensure that your aligner generated MD tags.

This is what i have and I do believe there is MD tags in them:
(base) [ntanduk@login01 PN2_SID100]$ samtools view -h PN2_SID100_bowtie2.bam | more 
@HD	VN:1.0	SO:coordinate
@SQ	SN:chr1	LN:308452471
.......
ATATTCAATAATACCGAAGGCTAACACGTACGGATTTTAGACCAAGAAATGGTCTCCACCAGAAATCCAAGAATGTGATCTATGGCAAGGAAACATATGT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF
FFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFF:FFFFFFFFFFF:FFFFFFFF:F:,FFFFFFFFFFFF:FFFFFF:FFF:FFFFF:FFFFFF	AS:i:-55	XS:i:-49	XN:i:0	XM:
i:11	XO:i:0	XG:i:0	NM:i:11	MD:Z:1C1A3A0A3C0C0A23C6T24C10T61	YS:i:-3	YT:Z:CP
A00600:293:H7HYFDSX7:1:1513:21811:17910	99	chr1	11142	1	143M	=	11397	398	CTGATAAATGGCCACACAACCCCCATTTTTTATGAAAATAGCC
ATGAGCGACCATTTTCAATAATATTAGAGGCTAAGACCTACGGATTTTTGACCAAGAAATGGTCTCCACCAGAAATCCAAGAATGTGATCTATGGCAAGG	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF,FFFFF:,,:FFFFF:F,FF:FFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	AS:i:-5	XS:i:-5	XN:i:0	XM:i:1	XO:i:0	XG:
i:0	NM:i:1	MD:Z:0A142	YS:i:0	YT:Z:CP
A00600:293:H7HYFDSX7:2:1436:13630:27790	147	chr1	11294	2	85M	=	10972	-407	TGGGGTTAGGTTTATGAGCCTCTGGTCGATGATCAATGGCCAC
ACAACCCCCATTTTTGTCGAAAATAGCCATGAACGACCATTT	F:FFF,:FFF:,FF,:FFF,FF,F,FFFFFF:FF:F:FF,F,FFF::FFFFFFFFFFFF:FFFFFF:FFFFFFFFFFFFFFFFFF	AS:i:-3	XS:

I have three 3 alignment software - bowtie2, minimap2, and bwa. I still get the same error. 
Any help is appreciated

**Comment by danshea** [comment]
Hi Nirwan,

You may have unaligned reads in the file. Have you tried filtering any unaligned reads prior to feeding it to IntroMap?

(i.e. - See https://www.biostars.org/p/56246/ on using samtools to confirm if there are any unmapped reads)

Regards,
Dan

**Comment by nirwan1265** [comment]
Yes. I removed the unmapped region and did the picard deduplication marking and it worked. thanks!!
